name: ci-labels

on:
  pull_request:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  handle-ci-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Call `build` workflow
        run: echo '${{ toJSON(github.event) }}'
