name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  foo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        result: ${{ fromJSON('[]') }}
    steps:
      - run: sleep 15
      - run: test '${{ matrix.result }}' == 'good'

  bar:
    needs: [foo]
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo 'bar'

  baz:
    needs: [bar]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'baz'
    
