name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
      - converted_to_draft

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}' | jq '.'
