name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  foo:
    runs-on: 'ubuntu-latest'
    steps:
      - run: echo 'Foo'
      
  bar:
    needs: foo
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
      - run: sleep 10

  baz:
    needs: bar
    runs-on: 'ubuntu-latest'
    steps:
      - run: echo 'Baz'
