name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  foo:
    runs-on: 'ubuntu-latest'
    outputs: 
      commit-sha: ${{ steps.commit-sha.outputs.commit-sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          sparse-checkout: |-
            .github/
            
      - name: Detect commit SHA
        id: commit-sha
        run: |
          echo "commit-sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set pending status
        env: 
          URL: /repos/renovate-testing/action-checks/statuses/${{ steps.commit-sha.outputs.commit-sha }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ env.URL }} \
            -f state='pending' \
            -f context='test-matrix' 
      
  bar:
    needs: foo
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
      - run: sleep 10

  baz:
    needs: [foo, bar]
    runs-on: 'ubuntu-latest'
    steps:
      - name: Set success status
        env: 
          URL: /repos/renovate-testing/action-checks/statuses/${{ needs.foo.outputs.commit-sha }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ env.URL }} \
            -f state='success' \
            -f context='test-matrix' 
