name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  foo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        result: ['good', 'good', 'bad']
    steps:
      - run: sleep 15
      - run: test '${{ matrix.result }}' == 'good'

  bar:
    needs: foo
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: return ${{ needs.foo.result == 'success' && 0 || 1 }}
    
