name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft

jobs:
  foo:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello'
      
  bar:
    if: always()
    needs: foo
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(needs.foo) }}'
  
