name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60

  bar:
    needs: foo
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: return ${{ needs.foo.result == 'success' && 0 || 1 }}
    
