name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  foo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON('[]') }}
    steps:
      - run: sleep 15
      - run: echo 'foo'

  bar:
    needs: [foo]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: echo 'bar'

  baz:
    needs: [bar]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: echo 'baz'
    
