name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  foo:
    runs-on: ubuntu-latest
    if: false
    strategy:
      matrix:
        result: ['good', 'good', 'bad']
    steps:
      - run: sleep 15
      - run: test '${{ matrix.result }}' == 'good'

  bar:
    needs: foo
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello'
    
